// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*TunnelMessage_Register
	//	*TunnelMessage_RegisterAck
	//	*TunnelMessage_ReqStart
	//	*TunnelMessage_ResStart
	//	*TunnelMessage_Error
	//	*TunnelMessage_Ping
	//	*TunnelMessage_Pong
	Msg           isTunnelMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetMsg() isTunnelMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *TunnelMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *TunnelMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *TunnelMessage) GetReqStart() *RequestStart {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_ReqStart); ok {
			return x.ReqStart
		}
	}
	return nil
}

func (x *TunnelMessage) GetResStart() *ResponseStart {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_ResStart); ok {
			return x.ResStart
		}
	}
	return nil
}

func (x *TunnelMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *TunnelMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *TunnelMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*TunnelMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isTunnelMessage_Msg interface {
	isTunnelMessage_Msg()
}

type TunnelMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type TunnelMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,2,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type TunnelMessage_ReqStart struct {
	ReqStart *RequestStart `protobuf:"bytes,10,opt,name=req_start,json=reqStart,proto3,oneof"`
}

type TunnelMessage_ResStart struct {
	ResStart *ResponseStart `protobuf:"bytes,20,opt,name=res_start,json=resStart,proto3,oneof"`
}

type TunnelMessage_Error struct {
	Error *Error `protobuf:"bytes,30,opt,name=error,proto3,oneof"`
}

type TunnelMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,40,opt,name=ping,proto3,oneof"`
}

type TunnelMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,41,opt,name=pong,proto3,oneof"`
}

func (*TunnelMessage_Register) isTunnelMessage_Msg() {}

func (*TunnelMessage_RegisterAck) isTunnelMessage_Msg() {}

func (*TunnelMessage_ReqStart) isTunnelMessage_Msg() {}

func (*TunnelMessage_ResStart) isTunnelMessage_Msg() {}

func (*TunnelMessage_Error) isTunnelMessage_Msg() {}

func (*TunnelMessage_Ping) isTunnelMessage_Msg() {}

func (*TunnelMessage_Pong) isTunnelMessage_Msg() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Services      []*Service             `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStart) Reset() {
	*x = RequestStart{}
	mi := &file_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStart) ProtoMessage() {}

func (x *RequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStart.ProtoReflect.Descriptor instead.
func (*RequestStart) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *RequestStart) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RequestStart) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RequestStart) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestStart) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ResponseStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStart) Reset() {
	*x = ResponseStart{}
	mi := &file_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStart) ProtoMessage() {}

func (x *ResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStart.ProtoReflect.Descriptor instead.
func (*ResponseStart) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseStart) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseStart) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResponseStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseStart) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *Ping) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *Pong) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\x0foutbound.tunnel\"\xa0\x03\n" +
	"\rTunnelMessage\x12>\n" +
	"\bregister\x18\x01 \x01(\v2 .outbound.tunnel.RegisterRequestH\x00R\bregister\x12A\n" +
	"\fregister_ack\x18\x02 \x01(\v2\x1c.outbound.tunnel.RegisterAckH\x00R\vregisterAck\x12<\n" +
	"\treq_start\x18\n" +
	" \x01(\v2\x1d.outbound.tunnel.RequestStartH\x00R\breqStart\x12=\n" +
	"\tres_start\x18\x14 \x01(\v2\x1e.outbound.tunnel.ResponseStartH\x00R\bresStart\x12.\n" +
	"\x05error\x18\x1e \x01(\v2\x16.outbound.tunnel.ErrorH\x00R\x05error\x12+\n" +
	"\x04ping\x18( \x01(\v2\x15.outbound.tunnel.PingH\x00R\x04ping\x12+\n" +
	"\x04pong\x18) \x01(\v2\x15.outbound.tunnel.PongH\x00R\x04pongB\x05\n" +
	"\x03msg\"b\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\bservices\x18\x02 \x03(\v2\x18.outbound.tunnel.ServiceR\bservices\"1\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"7\n" +
	"\vRegisterAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa4\x02\n" +
	"\fRequestStart\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12D\n" +
	"\aheaders\x18\x06 \x03(\v2*.outbound.tunnel.RequestStart.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\rResponseStart\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.outbound.tunnel.ResponseStart.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x05Error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs2`\n" +
	"\rTunnelService\x12O\n" +
	"\aConnect\x12\x1e.outbound.tunnel.TunnelMessage\x1a\x1e.outbound.tunnel.TunnelMessage\"\x00(\x010\x01B\x19Z\x17outbound/proto;tunnelpbb\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_tunnel_proto_goTypes = []any{
	(*TunnelMessage)(nil),   // 0: outbound.tunnel.TunnelMessage
	(*RegisterRequest)(nil), // 1: outbound.tunnel.RegisterRequest
	(*Service)(nil),         // 2: outbound.tunnel.Service
	(*RegisterAck)(nil),     // 3: outbound.tunnel.RegisterAck
	(*RequestStart)(nil),    // 4: outbound.tunnel.RequestStart
	(*ResponseStart)(nil),   // 5: outbound.tunnel.ResponseStart
	(*Error)(nil),           // 6: outbound.tunnel.Error
	(*Ping)(nil),            // 7: outbound.tunnel.Ping
	(*Pong)(nil),            // 8: outbound.tunnel.Pong
	nil,                     // 9: outbound.tunnel.RequestStart.HeadersEntry
	nil,                     // 10: outbound.tunnel.ResponseStart.HeadersEntry
}
var file_proto_tunnel_proto_depIdxs = []int32{
	1,  // 0: outbound.tunnel.TunnelMessage.register:type_name -> outbound.tunnel.RegisterRequest
	3,  // 1: outbound.tunnel.TunnelMessage.register_ack:type_name -> outbound.tunnel.RegisterAck
	4,  // 2: outbound.tunnel.TunnelMessage.req_start:type_name -> outbound.tunnel.RequestStart
	5,  // 3: outbound.tunnel.TunnelMessage.res_start:type_name -> outbound.tunnel.ResponseStart
	6,  // 4: outbound.tunnel.TunnelMessage.error:type_name -> outbound.tunnel.Error
	7,  // 5: outbound.tunnel.TunnelMessage.ping:type_name -> outbound.tunnel.Ping
	8,  // 6: outbound.tunnel.TunnelMessage.pong:type_name -> outbound.tunnel.Pong
	2,  // 7: outbound.tunnel.RegisterRequest.services:type_name -> outbound.tunnel.Service
	9,  // 8: outbound.tunnel.RequestStart.headers:type_name -> outbound.tunnel.RequestStart.HeadersEntry
	10, // 9: outbound.tunnel.ResponseStart.headers:type_name -> outbound.tunnel.ResponseStart.HeadersEntry
	0,  // 10: outbound.tunnel.TunnelService.Connect:input_type -> outbound.tunnel.TunnelMessage
	0,  // 11: outbound.tunnel.TunnelService.Connect:output_type -> outbound.tunnel.TunnelMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_Register)(nil),
		(*TunnelMessage_RegisterAck)(nil),
		(*TunnelMessage_ReqStart)(nil),
		(*TunnelMessage_ResStart)(nil),
		(*TunnelMessage_Error)(nil),
		(*TunnelMessage_Ping)(nil),
		(*TunnelMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
